version: '2'

services:
  app:
    image: php-apache
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80
    restart: unless-stopped

  database:
    image: mysql:8.0.0
    environment:
      MYSQL_USER: "admin-lms"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "laravel-lms"
      MYSQL_ROOT_PASSWORD: "rootpass"  
    ports:
      - 8306:3306
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8082:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpass  
    restart: unless-stopped

volumes:
  database:
