version: '2'

services:
  app:
    image: php-apache
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./:/var/www/html
    ports:
      - 8081:80

  database:
    image: mysql:8.0.0
    environment:
      MYSQL_USER: "lms"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "laravel-lms-docker"
      MYSQL_ROOT_PASSWORD: "rootpass"  
    ports:
      - 8306:3306
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8082:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpass  

volumes:
  database:







# # local development disarankan pakai versi 2, untuk production versi 3
# version: '2'

# services:
#   # menjalankan docker yg sudah dibuat
#   app:
#     image: php-apache
#     links:
#       - database
#     depends_on:
#       - database
#     # semua yg ada di project di-binding/mounting ke directory container
#     # Semua file & folder dari host (VSCode kamu) akan tersinkron otomatis ke direktori /var/www/html di dalam container.
#     volumes:
#       - ./:/var/www/html
#     # mapping port yg akan digunakan
#     ports:
#       - 8081:80
#       # host:container

#   database:
#     image: mysql:8.0.0
#     # konfigurasi yg digunakan mysql  
#     environment:
#       MYSQL_USER: "lms"
#       MYSQL_PASSWORD: "password"
#       MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#       MYSQL_DATABASE: "laravel-lms-docker"
#     # mapping port yg akan digunakan
#     ports:
#       - 8307:3306
#       # host:container
#     volumes:
#       - database:/var/lib/mysql

# volumes:
#   database: